Создание сцены в виртуальной реальности, где можно стрелять по мишени с bhaptic
RTUITLab/RevolIT pull request #14
Opened 2021-05-11 23:22 UTC by mentoster

close #8 
close #3 
close #6

2021-05-13 20:32 UTC, Delivery-Klad commented
> close #8
> close #3
> close #6

8 не закрыт

2021-05-14 08:13 UTC, mentoster commented
> > close #8
> > close #3
> > close #6
> 
> 8 не закрыт

Пистолет вызывает метод у жилета, только если на нём стоит тег player
Я поставил лог, если метод был вызван

https://github.com/mentoster/RevolIT-1/blob/master/Assets/Scripts/Colt/BhapticConnect.cs

2021-05-14 10:34 UTC, mentoster commented
Система очков **адаптивная**
Можно менять коэффициент за попадание в ногу голову или тело
**Сейчас стоит:**

- Урон - **30**, очков за урон - **30**
- Попадание в голову : **2x** урона и очков
- Попадание в тело : **1x** урона и очков
- Попадание в другие участки тела : **0.5x** урона и очков
- Убийство : +**50** очков

https://user-images.githubusercontent.com/50594730/118258551-ad55de00-b4b8-11eb-8216-a3e6df410b02.mp4

2021-05-14 16:27 UTC, Delivery-Klad commented
> > > close #8
> > > close #3
> > > close #6
> > 
> > 
> > 8 не закрыт
> 
> Пистолет вызывает метод у жилета, только если на нём стоит тег player
> Я поставил лог, если метод был вызван
> 
> https://github.com/mentoster/RevolIT-1/blob/master/Assets/Scripts/Colt/BhapticConnect.cs
> 
> Вызов метода снижение жизней тоже есть
> https://github.com/mentoster/RevolIT-1/blob/master/Assets/Scripts/Colt/Target.cs
> 
> Но вызов его пока в закоменчен, логика эффектов тоже есть
> ![image](https://user-images.githubusercontent.com/50594730/118249639-4af7e000-b4ae-11eb-84fb-f017d83910d0.png)

8 таск подразумевает онлайн, которого нет

2021-05-14 17:17 UTC, leonis13579 requested changes
Слишком много файлов. Требуется почистить лишние не используемые файлы и потом обновить PR.

2021-05-20 14:10 UTC, leonis13579 approved these changes
Вроде все ок

2021-05-24 10:09 UTC, merged